// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/admin/[kvitto].tsx";
import * as $1 from "./routes/admin/index.tsx";
import * as $2 from "./routes/index.tsx";
import * as $3 from "./routes/test.tsx";
import * as $$0 from "./islands/AdminKvitton.tsx";
import * as $$1 from "./islands/FormSkicka.tsx";

const manifest = {
  routes: {
    "./routes/admin/[kvitto].tsx": $0,
    "./routes/admin/index.tsx": $1,
    "./routes/index.tsx": $2,
    "./routes/test.tsx": $3,
  },
  islands: {
    "./islands/AdminKvitton.tsx": $$0,
    "./islands/FormSkicka.tsx": $$1,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
